### ISSUE TITLE
一部グリフの不具合（筆画や部品の欠落）

### ISSUE THREAD

**Issue by lakejason0** [ge9/NazonoMincho#2] opened 2023-01-25 13:35 UTC
U+317D9:
![image](https://user-images.githubusercontent.com/36039861/214577107-5f34c790-0bb5-4741-bbbb-c594c464cefd.png)
U+3185A:
![image](https://user-images.githubusercontent.com/36039861/214577147-75038de8-96ba-43be-868e-2f3ec21cc68e.png)
This is an incomplete list. There are other glyphs that are missing strokes as well.

**Comment by onichan0923** [comment] 2023-01-25 14:52
これもです
U+8496
![Screenshot_2023-01-25-22-51-46-74_c6d2f5838c1fca5283099d09ba458d93](https://user-images.githubusercontent.com/68043613/214595453-053bfb8e-c826-4751-8d41-a30d7c4485c9.jpg)

**Comment by Partyb0ssishere** [comment] 2023-01-25 14:55
These characters also have the same problem:  
**(show as unicode code-points)**  
5304  
5678  
5DD3  
5FCC  
655C  
8352  
8496  
8614  
9078  
9E0B  
21FEB  
241AC  
29C7F  
2BEDB  
2F945  
30034  
30EF5  
3141E  
31AE5  
31F4A  
32325

**Comment by ge9** [comment] 2023-01-25 15:04
Thank you for many helpful examples.
I tested the first two characters, and this seems due to Inkscape, which I use to unite paths.
I confirmed by applying "Path -> Union" to the following SVG files:
![u3185a](https://user-images.githubusercontent.com/37699433/214596675-11803b2a-6f23-4f6f-baad-142e064830b7.svg)
![u317d9](https://user-images.githubusercontent.com/37699433/214596685-2e69c98a-3a89-4ad4-8ef4-50d277b586f0.svg)
I'll search for workarounds.

**Comment by onichan0923** [comment] 2023-01-25 15:48
NazoMin Regularには、下書きのグリフが不具合を発見した
匄噸巓忌敜荒蒖蘔選鸋𡿫𤆬𩱿𫻛眞𰀴𰻵𱐞𱫥𱽊𲌥
![Screenshot_2023-01-25-23-05-34-78_c37d74246d9c81aa0bb824b57eaf7062](https://user-images.githubusercontent.com/68043613/214608637-065d3668-2ae8-423c-a144-7597e4ab71da.jpg)

NazoMin Mediumには
匄忌敜荒蘔𰻵𱐞𱽊
![Screenshot_2023-01-25-23-05-42-63_c37d74246d9c81aa0bb824b57eaf7062](https://user-images.githubusercontent.com/68043613/214608657-5db8c05e-cf19-493c-9051-526a142c04e0.jpg)

NazoMin+ Mediumには
𠅳𠖕𠛋𠜡𠲹𡧽𡫃𡬁𡬃𡬗𡬛𡮭𡴣𢁎𢂪𢌴𢚢𢛖𢣫𢣳𢻬𢻴𣎽𣪘𤅘𤉂𤋞𥁃𥔊𥛤𦒲𦮼𧓟𧕝𧡺𧧄𨚋𨚔𨛑𨞑𨽻𩣐𪁬𫉏𫟎𫶻𫹾𫺴𬯮𭣑𮎁
![Screenshot_2023-01-25-23-39-41-49_1a2cc437684de46a6b60c4abbf3e4a5c](https://user-images.githubusercontent.com/68043613/214608696-a64637bb-d1f6-4ede-a2b9-31c5a9788c23.jpg)

肉眼で発見されたため、全てではないかも知れません。
不具合修正に期待。
お疲れ様でした。

**Comment by ge9** [comment] 2023-01-26 08:32
Thank you.
I attached our examples to the existing Inkscape bug report: https://gitlab.com/inkscape/inbox/-/issues/6886
I also tried Fontforge for path union, but it was also buggy.
So I'm afraid this cannot be fixed right now, but I'll continue to look for any workarounds.

**Comment by ge9** [comment] 2023-01-27 02:28
Apparently all of broken glyphs contained "曲げ" strokes, I modified https://github.com/ge9/kage-engine-2 to manually "unite" polygons of "曲げ" strokes, and at least characters listed here were all fixed.
See release https://github.com/ge9/NazonoMincho/releases/tag/0.003 .
I'm not sure all other glyphs work fine, but I close this as of now.

**Closed as completed by ge9** 2023-01-27 02:28 UTC
